### ISSUE TITLE
LV Lane dataset

### ISSUE THREAD

**Issue by adeelahmedrana** [zillur-av/LVLane#1]
Hi, i wanted to run your code but the LV dataset is not reachable with the link you provided. 
The Link takes you back to the original repo page.
Is it possible for you to share the weights with me it will save me a lot of hassle training the network.
Many thanks

**Comment by zillur01** [comment]
Thanks for your interest. I apologize for the inconvenience. Our paper just got accepted and we are still working on updating this repo. Hopefully you will get it within 2-3 days.

**Comment by zillur01** [comment]
@adeelahmedrana I updated the links. You can download the dataset now.
