### ISSUE TITLE
Pre-trained weights 

### ISSUE THREAD

**Issue by So-nja** [zillur-av/LVLane#2]
Thanks for your great work.
Unfortunately, the pre-trained weights seem to be trained with the Tusimple dataset only.
I would like to reproduce the results in your paper, so could you share the weights trained with the Tusimple and LVLane datasets?
Many thanks!

**Comment by zillur01** [comment]
> Thanks for your great work. Unfortunately, the pre-trained weights seem to be trained with the Tusimple dataset only. I would like to reproduce the results in your paper, so could you share the weights trained with the Tusimple and LVLane datasets? Many thanks!

Sorry for late reply. I updated the weights.
