### ISSUE TITLE
Problems with reading tusimple data

### ISSUE THREAD

**Issue by huashuzi** [zillur-av/LVLane#21]
Thank you very much author for your work!
Can I ask you about line 67 in lanedet/datasets/process/base_dataset.py:
~~~
category = [0 if np.all(sample['cls_label'][:,i].numpy() == 100) else category[i] for i in range(6)]
~~~
What does the 6 in range(6) mean here.
In fact when I use tusimple, my label format is:
~~~
{"lanes": [[-2, -2, ... , -2], [-2, -2, ... , 87], [-2, -2, ... , -2], [-2, -2, ... , -2]], [-2, -2, ... , -2]], "h_samples": [160, 170, ... , 710], "raw_file": "clips/0601/1494453497604532231/20.jpg", "categories": [1, 3, 3, 2]}
~~~
The length of the categories list here is 4, unlike 6.
How do I fix this problem, just simply replace 6 with 4?
I am very much looking forward to your answer, best wishes!

**Comment by huashuzi** [comment]
Using the json file generated by the tools/generate_seg_tusimple.py script provided by the author, the list of categories generated is 6 columns。

**Comment by ZQEzekiel** [comment]
Hello, have you successfully set up the dataset? I encountered the following problem when using test_label_classes.txt to generate a new .JSON:
python tools/generate_seg_tusimple.py --root $DATASETROOT --filename 'test_label'
generating masks...
Traceback (most recent call last):
File "tools/generate_seg_tusimple.py", line 112, in
generate_label(args)
File "tools/generate_seg_tusimple.py", line 102, in generate_label
gen_label_from_json(args.root, save_dir, file_name = args.filename)
File "tools/generate_seg_tusimple.py", line 84, in gen_label_from_json
cv2.imwrite(seg_path, seg_img)
cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:708: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'imwrite_'
Looking forward to your reply, thank you!
If you are willing, I hope to communicate with you via email. This is my email address: 1356154755zq@gmail.com

**Comment by gabaebae123** [comment]
> Hello, have you successfully set up the dataset? I encountered the following problem when using test_label_classes.txt to generate a new .JSON: python tools/generate_seg_tusimple.py --root $DATASETROOT --filename 'test_label' generating masks... Traceback (most recent call last): File "tools/generate_seg_tusimple.py", line 112, in generate_label(args) File "tools/generate_seg_tusimple.py", line 102, in generate_label gen_label_from_json(args.root, save_dir, file_name = args.filename) File "tools/generate_seg_tusimple.py", line 84, in gen_label_from_json cv2.imwrite(seg_path, seg_img) cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:708: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'imwrite_' Looking forward to your reply, thank you! If you are willing, I hope to communicate with you via email. This is my email address: [1356154755zq@gmail.com](mailto:1356154755zq@gmail.com)

Hello!Have you solved this problem? Now I get the same error.

**Comment by ZQEzekiel** [comment]
> > Hello, have you successfully set up the dataset? I encountered the following problem when using test_label_classes.txt to generate a new .JSON: python tools/generate_seg_tusimple.py --root $DATASETROOT --filename 'test_label' generating masks... Traceback (most recent call last): File "tools/generate_seg_tusimple.py", line 112, in generate_label(args) File "tools/generate_seg_tusimple.py", line 102, in generate_label gen_label_from_json(args.root, save_dir, file_name = args.filename) File "tools/generate_seg_tusimple.py", line 84, in gen_label_from_json cv2.imwrite(seg_path, seg_img) cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:708: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'imwrite_' Looking forward to your reply, thank you! If you are willing, I hope to communicate with you via email. This is my email address: [1356154755zq@gmail.com](mailto:1356154755zq@gmail.com)您好，您已成功设置数据集吗？我在使用 test_label_classes.txt 生成新的 .JSON： python tools/generate_seg_tusimple.py --root $DATASETROOT --filename 'test_label' 生成掩码...回溯（最近调用最后一次）：文件“tools/generate_seg_tusimple.py”，第 112 行，generate_label（args） 文件“tools/generate_seg_tusimple.py”，第 102 行，generate_label gen_label_from_json（args.root， save_dir， file_name = args.filename） 文件“tools/generate_seg_tusimple.py”，第 84 行，gen_label_from_json cv2.imwrite（seg_path， seg_img） cv2.error： OpenCV（4.10.0） /io/opencv/modules/imgcodecs/src/loadsave.cpp：708： 错误：（-2：未指定的错误）在函数 'imwrite_' 中找不到指定扩展名的写入器期待您的回复，谢谢！如果您愿意，我希望通过电子邮件与您沟通。这是我的电子邮件地址：[1356154755zq@gmail.com](mailto:1356154755zq@gmail.com)
> 
> Hello!Have you solved this problem? Now I get the same error.你好！你解决了这个问题吗？现在我收到同样的错误。

# 修改路径处理逻辑，假设路径深度为4
                seg_path_split = img_path.split("/")
                if len(seg_path_split) == 4:
                    # 对于 "clips/0530/1492626760788443246_0/20.jpg"
                    seg_path = os.path.join(data_root, data_savedir, seg_path_split[1], seg_path_split[2])
                    img_name = seg_path_split[3]
                elif len(seg_path_split) == 3:
                    # 对于 "clips/LVLane_test_sunny/lane_images_sunny_20230123150433355132.jpg"
                    seg_path = os.path.join(data_root, data_savedir, seg_path_split[1])
                    img_name = seg_path_split[2]
                else:
                    raise ValueError(f"Unexpected raw_file path format: {img_path}")

                os.makedirs(seg_path, exist_ok=True)
                # 确保正确移除扩展名并添加 .png
                if '.' in img_name:
                    seg_filename = img_name.rsplit('.', 1)[0] + ".png"
                else:
                    seg_filename = img_name + ".png"  # 如果没有扩展名，直接添加 .png
                seg_path = os.path.join(seg_path, seg_filename)
                
                # 调试输出（可选）
                # print(f"Saving segmentation mask to: {seg_path}")

                # 保存分割图像
                cv2.imwrite(seg_path, seg_img)
                
You can try this code (generated by AI), the specific reason should be that the folder path length of the original tusimple dataset is different from that of lvlane here
