### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'cat_dim'

### ISSUE THREAD

**Issue by huashuzi** [zillur-av/LVLane#22]
Generate CULaneV1 JSON with categories according to the steps in `readme.md`, then run the command
~~~
 (lanedet) root@autodl-container-d6ee47a7e9-14528d71:~/Project/LVLane# python main.py configs/ufld/resnet18_culane.py --gpus 0
~~~
Returns the error:
~~~
Traceback (most recent call last).
  File "main.py", line 71, in <module>
    main()
  File "main.py", line 30, in main
    runner = Runner(cfg)
  File "/root/Project/LVLane/lanedet/engine/runner.py", line 26, in __init__
    self.net = build_net(self.cfg)
  File "/root/Project/LVLane/lanedet/models/registry.py", line 32, in build_net
    return build(cfg.net, NETS, default_args=dict(cfg=cfg))
  File "/root/Project/LVLane/lanedet/models/registry.py", line 16, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/root/Project/LVLane/lanedet/utils/registry.py", line 85, in build_from_cfg
    return obj_cls(**args)
  File "/root/Project/LVLane/lanedet/models/nets/detector.py", line 16, in __init__
    self.heads = build_heads(cfg)
  File "/root/Project/LVLane/lanedet/models/registry.py", line 26, in build_heads
    return build(cfg.heads, HEADS, default_args=dict(cfg=cfg))
  File "/root/Project/LVLane/lanedet/models/registry.py", line 16, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/root/Project/LVLane/lanedet/utils/registry.py", line 85, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() missing 1 required positional argument: 'cat_dim'
~~~

What does this argument mean? How do I troubleshoot this error?

Translated with DeepL.com (free version)

**Comment by huashuzi** [comment]
The mistake made was to confuse the `CULane` dataset with the `LVLaneV1` dataset. The `LVLaneV1` dataset should be organized as `TuSimple`. And change the `lanedet/datasets/tusimple.py` as follows:
~~~
SPLIT_FILES = {    
    ## tusimple
    # 'test': ['test_label.json']

    ## lvlanev1
    'trainval': ['LVLane_train_sunny.json'], ## lvlanev1
    'val': ['LVLane_test_sunny.json'],
    'test': ['LVLane_test_sunny.json']
}
~~~
In addition the organization of the dataset folder should be consistent with the author's example `tusimple`; the `configs/ufld/resnet18_tusimple.py` file also needs to be modified with the relevant parameters.
Thanks again to the authors for their contribution!

----
所犯错误，把`CULane`数据集和`LVLaneV1`数据集混淆了。`LVLaneV1`数据集应该用`TuSimple`的形式组织起来。并在`lanedet/datasets/tusimple.py`修改如下：
~~~
SPLIT_FILES = {    
    ## tusimple
    # 'trainval': ['label_data_0313.json', 'label_data_0601.json', 'label_data_0531.json'],
    # 'val': ['test_label.json'],
    # 'test': ['test_label.json']

    ## lvlanev1
    'trainval': ['LVLane_train_sunny.json'],
    'val': ['LVLane_test_sunny.json'],
    'test': ['LVLane_test_sunny.json']
}
~~~
此外数据集文件夹的组织结构要与作者举例`tusimple`的一致; `configs/ufld/resnet18_tusimple.py`文件中同样需要修改相关参数。
再次感谢作者的贡献！

**Comment by gabaebae123** [comment]
> The mistake made was to confuse the `CULane` dataset with the `LVLaneV1` dataset. The `LVLaneV1` dataset should be organized as `TuSimple`. And change the `lanedet/datasets/tusimple.py` as follows:
> 
> ```
> SPLIT_FILES = {    
>     ## tusimple
>     # 'test': ['test_label.json']
> 
>     ## lvlanev1
>     'trainval': ['LVLane_train_sunny.json'], ## lvlanev1
>     'val': ['LVLane_test_sunny.json'],
>     'test': ['LVLane_test_sunny.json']
> }
> ```
> 
> In addition the organization of the dataset folder should be consistent with the author's example `tusimple`; the `configs/ufld/resnet18_tusimple.py` file also needs to be modified with the relevant parameters. Thanks again to the authors for their contribution!
> 
> 所犯错误，把`CULane`数据集和`LVLaneV1`数据集混淆了。`LVLaneV1`数据集应该用`TuSimple`的形式组织起来。并在`lanedet/datasets/tusimple.py`修改如下：
> 
> ```
> SPLIT_FILES = {    
>     ## tusimple
>     # 'trainval': ['label_data_0313.json', 'label_data_0601.json', 'label_data_0531.json'],
>     # 'val': ['test_label.json'],
>     # 'test': ['test_label.json']
> 
>     ## lvlanev1
>     'trainval': ['LVLane_train_sunny.json'],
>     'val': ['LVLane_test_sunny.json'],
>     'test': ['LVLane_test_sunny.json']
> }
> ```
> 
> 此外数据集文件夹的组织结构要与作者举例`tusimple`的一致; `configs/ufld/resnet18_tusimple.py`文件中同样需要修改相关参数。 再次感谢作者的贡献！

如果数据集里面既有tusimple又有lvlane数据，该怎么办呢？
