### ISSUE TITLE
About classification output visualization

### ISSUE THREAD

**Issue by Choi-YeongJoon** [zillur-av/LVLane#3]
Thanks for your work!! I tried to classify lane class using LVLane(config is resa-18, dataset is TuSimple). I got a result, but it has only information about lane detect coords.
How can I get result about detected lane category?

**Comment by Choi-YeongJoon** [comment]
I found Inference code. So, I could get result about detected lane category. Thank you very much!

**Comment by gabaebae123** [comment]
> I found Inference code. So, I could get result about detected lane category. Thank you very much!

Hello! How do you generate tusimple datasets with categories?
