### ISSUE TITLE
tusimple训练集没有给车道线类别

### ISSUE THREAD

**Issue by xuefei4545** [zillur-av/LVLane#5]
你好，我在复现训练代码的时候，发现您给的dataset链接中并没有给出Tusimple训练数据集的车道线种类，只提供了test的车道线种类，请问可以提供一下train的种类吗，还是说不需要train种类也可以训练呢

**Comment by zillur01** [comment]
You can find those in https://github.com/fabvio/TuSimple-lane-classes

**Comment by liyufan** [comment]
> You can find those in https://github.com/fabvio/TuSimple-lane-classes

Could you provide a category label for the TuSimple test set?
