### ISSUE TITLE
Training problem about my own dataset

### ISSUE THREAD

**Issue by xiaoxiaoyi689** [zillur-av/LVLane#7]
Hi author，thanks for your great work!

I have created my dataset which is same form as Tusimple dataset. My image size is 1080x1920，and I have changed  the image size from the files  "tools/generate_seg_tusimple.py" and "configs/ufld/resnet18_tusimple.py". But when training, the ''classification accuracy''  keeps increasing to about 94%, while "detection metric" grows slowly and stops growing at about 39%.  The test results are as follows;
![截图 2023-11-10 15-42-07](https://github.com/zillur-av/LVLane/assets/75001583/3dd3ec67-aaa6-4cb3-b61d-07d7be54f968)

**Comment by xiaoxiaoyi689** [comment]
I don't know if this problem has anything to do with the size of the my dataset, and my training set is only 500 images

**Comment by zillur01** [comment]
It has nothing to do with dataset size but the resolution of images. The best way to handle this would be resize your images to 1280x720 and modify annotations proportionately as well. Another quick step you can take is to modify these lines https://github.com/zillur-av/LVLane/blob/f89d53d63b45069fdae6689157c7f33caa6c8652/configs/ufld/resnet18_tusimple.py#L56-L61

Change `orig_img_h, orig_img_w, sample_y`. For example, if your images are 1920x1080, you can change `sample_y` to `range(1070, 450, -10)` something like that. It depends on how many lane points you have in your training images. Like I had 56 points from 150 to 710 and I used 56 here https://github.com/zillur-av/LVLane/blob/f89d53d63b45069fdae6689157c7f33caa6c8652/configs/ufld/resnet18_tusimple.py#L20-L22
Probably you need to change that as well. Check your json labels to know from where you start annotating your lane points. Just give it a shot and let me know.

**Comment by xiaoxiaoyi689** [comment]
Thank you for your reply. I will tell you the experimental results as soon as possible

**Comment by xiaoxiaoyi689** [comment]
Hi,  author,  I have solved the above problem. I scaled the image to 1280x720 , and modify the annotations. Finally,  both the training and test results looked  normal. Thanks again for your help.

**Comment by gabaebae123** [comment]
> Hi, author, I have solved the above problem. I scaled the image to 1280x720 , and modify the annotations. Finally, both the training and test results looked normal. Thanks again for your help.

Could you tell me how you make your own data set?
