### ISSUE TITLE
Classification

### ISSUE THREAD

**Issue by Chen-Philiek** [zillur-av/LVLane#8]
Hello, in fact, i would like to extract the classification part from your project in order to test it with another lane detection project that i am working on. But i can't find the way to do this. Can you tell me if it's possible to extract this part ? or should i just rewrite the code myself please!

**Comment by zillur01** [comment]
It can be done depending on your detection network. Let's see if you can take a feature map out of the detector and feed it to the classification branch. Maybe try to one in between your feature extractor (backbone) and detection branch

**Comment by Chen-Philiek** [comment]
Hi, what did you put for your input ? Did u just put an image as input or did you give the coordinates of the lines as input ?

**Comment by Chen-Philiek** [comment]
i found the way to solve the problem
